apiVersion: v1
kind: Service
metadata:
  name: ide-fastapi-svc
spec:
  selector:
    app: ide-fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
