apiVersion: v1
kind: Pod
metadata:
  name: vnc-test
  namespace: webide-net
spec:
  containers:
    - name: vnc
      image: jaewoo6257/vnc:1.0.0
      ports:
        - containerPort: 6080
        - containerPort: 5900

# kubectl apply -f vnc-pod.yaml